Repository babajka/babajka-frontend, pull requests merged in 2018-04, with the labels that each got.

#19 New routing + Lang switching
  .eslintrc.js
  components/articles/ArticleLink.js
  components/articles/ArticlePreview.js
  components/articles/PublicArticle.js
  components/articles/SpecialHeading.js
  components/articles/edit/EditArticleForm.js
  components/articles/edit/EditLocaleForm.js
  components/articles/grid/ArticlesRow.js
  components/common/ExternalLink.js
  components/common/Footer.js
  components/common/Header.js
  components/common/Icon.js
  components/common/LanguageSwitcher.js
  components/common/Link.js
  components/common/LocaleContext.js
  components/common/PageLayout.js
  components/common/common.stories.js
  components/common/layout/CoreLayout.js
  components/common/layout/Footer.js
  components/common/layout/Header.js
  components/common/layout/PageLayout.js
  constants/dictionary.js
  constants/index.js
  constants/routing.js
  constants/social.js
  package-lock.json
  package.json
  pages/about.js
  pages/article.js
  pages/collections.js
  pages/index.js
  pages/login.js
  pages/partners.js
  redux/ducks/articles.js
  redux/ducks/diary.js
  routes.js
  server.js
  utils/getters.js
Labels: feature

#20 i18n
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  bin/copy-static.sh
  bin/fetchDict.js
  components/articles/ArticlePreview.js
  components/articles/Author.js
  components/articles/SpecialHeading.js
  components/auth/FormField.js
  components/auth/LoginForm.js
  components/auth/auth.stories.js
  components/common/Text.js
  components/common/common.stories.js
  components/common/layout/Footer.js
  components/common/layout/Header.js
  constants/dictionary.js
  package-lock.json
  package.json
  pages/index.js
  pm2-config.json
  routes.js
  server.js
  utils/customPropTypes.js
  utils/getters.js
  utils/validators.js
Labels: feature

#21 Edit article
  bin/fetchDict.js
  components/articles/Author.js
  components/articles/PublicArticle.js
  components/articles/edit/EditArticleForm.js
  components/articles/edit/EditLocaleForm.js
  components/articles/edit/Editor.js
  components/auth/LoginForm.js
  components/common/Link.js
  components/common/Select.js
  components/common/layout/CoreLayout.js
  components/common/layout/Header.js
  constants/api.js
  package-lock.json
  package.json
  pages/article.js
  redux/ducks/articles.js
  routes.js
  utils/customPropTypes.js
  utils/getters.js
  utils/validators.js
Labels: feature, refactor

#23 Minor fixes to enable static delivery by nginx
  bin/copy-static.sh
  components/common/layout/CoreLayout.js
  components/common/layout/Header.js
  package-lock.json
  package.json
Labels: fix

#24 Minor Backend compatibility updates
  README.md
  components/articles/PublicArticle.js
  components/articles/articles.stories.js
  components/common/StoriesDecorator.js
  components/common/Text.js
  components/common/layout/CoreLayout.js
  components/common/layout/Header.js
  components/common/layout/PageLayout.js
  constants/server.js
  constants/social.js
  env-config.js
  package-lock.json
  package.json
  pages/about.js
  pages/article.js
  pages/collections.js
  pages/index.js
  pages/login.js
  pages/partners.js
  redux/ducks/articles.js
  redux/ducks/auth.js
  redux/middlewares/analytics.js
  redux/store.js
  routes.js
  server.js
  utils/getters.js
  utils/request.js
Labels: fix

#25 About page and Team data fetching
  .gitignore
  README.md
  bin/fetchDict.js
  bin/fetchTeam.js
  components/about/TeamRow.js
  components/common/Text.js
  constants/social.js
  data/.gitkeep
  package.json
  pages/about.js
  pages/index.js
  routes.js
  utils/getters.js
Labels: feature
