Repository babajka/babajka-frontend, pull requests merged in 2018-06, with the labels that each got.

#28 Quick fix for incomplete rows on main page
  bin/fetchDict.js
  components/about/TeamRow.js
  components/articles/grid/ArticlesRow.js
  constants/server.js
  constants/social.js
  package-lock.json
  package.json
  pages/about.js
  pm2-config.json
  utils/getters.js
Labels: fix

#31 🔥Main Page & Login Updates
  components/about/TeamRow.js
  components/articles/ArticlePreview.js
  components/articles/Author.js
  components/articles/Diary.js
  components/articles/PublicArticle.js
  components/articles/edit/EditArticleForm.js
  components/articles/edit/EditLocaleForm.js
  components/articles/grid/ArticlesComplexRow.js
  components/articles/grid/ArticlesRow.js
  components/articles/public/AuthorBlock.js
  components/articles/public/EditLink.js
  components/articles/public/PublishInfo.js
  components/articles/public/ShareToButton.js
  components/auth/FormField.js
  components/auth/LoginForm.js
  components/auth/auth.stories.js
  components/common/Button.js
  components/common/CompleteRow.js
  components/common/Icon.js
  components/common/Modal.js
  components/common/Select.js
  components/common/TextWithBr.js
  components/common/layout/Header.js
  constants/articles.js
  constants/social.js
  package-lock.json
  package.json
  pages/index.js
  pages/login.js
  redux/ducks/articles.js
  redux/ducks/auth.js
  redux/middlewares/analytics.js
  utils/customPropTypes.js
  utils/formatters.js
  utils/getters.js
  utils/request.js
Labels: feature, fix, refactor

#32 Refactoring and updates
  .babelrc
  .eslintrc.js
  .gitignore
  .storybook/.babelrc
  README.md
  components/articles/ArticlePreview/Author.js
  components/articles/ArticlePreview/SpecialHeading.js
  components/articles/ArticlePreview/index.js
  components/articles/ArticlesComplexRow.js
  components/articles/ArticlesRow.js
  components/articles/EditArticleForm/EditLocaleForm.js
  components/articles/EditArticleForm/Editor.js
  components/articles/EditArticleForm/index.js
  components/articles/PublicArticle/Arrow.js
  components/articles/PublicArticle/AuthorBlock.js
  components/articles/PublicArticle/CollectionBlock.js
  components/articles/PublicArticle/EditLink.js
  components/articles/PublicArticle/InfoIcon.js
  components/articles/PublicArticle/PublishInfo.js
  components/articles/PublicArticle/ShareToButton.js
  components/articles/PublicArticle/index.js
  components/common/CompleteRow.js
  components/common/Text.js
  components/common/layout/CoreLayout.js
  components/specials/Diary.js
  constants/server.js
  env-config.js
  next.config.js
  package-lock.json
  package.json
  pages/about.js
  pages/editArticle.js
  pages/index.js
  redux/store.js
  server.js
Labels: fix, refactor

#33 Minor UI improvements
  components/articles/ArticlePreview/index.js
  package-lock.json
  pm2-config.json
Labels: feature

#30 Dante Editor
  .babelrc
  bin/copy-static.sh
  components/articles/ArticlePreview/index.js
  components/articles/EditArticleForm/EditLocaleForm.js
  components/articles/EditArticleForm/Editor.js
  components/articles/EditArticleForm/index.js
  components/articles/PublicArticle/index.js
  components/auth/LoginForm.js
  components/common/Button.js
  components/common/Editor/config.js
  components/common/Editor/content.json
  components/common/Editor/index.js
  components/common/Editor/tooltips.js
  components/common/Editor/widgets.js
  components/common/Renderer/index.js
  components/common/Renderer/renderers.js
  components/common/Select.js
  package-lock.json
  package.json
  pages/editorTest.js
  pages/index.js
  redux/ducks/articles.js
  routes.js
  utils/customPropTypes.js
  utils/getters.js
  utils/redux.js
  utils/validators.js
Labels: feature, refactor

#34 Sharing to Social Networks
  .eslintrc.js
  components/articles/PublicArticle/ShareToButton.js
  components/articles/PublicArticle/index.js
  components/common/layout/CoreLayout.js
  constants/index.js
  constants/server.js
  constants/social.js
  next.config.js
  package-lock.json
  package.json
  pm2-config.json
  server.js
  utils/args.js
Labels: feature

#35 Edit article final fix
  bin/copy-static.sh
  components/articles/EditArticleForm/Author.js
  components/articles/EditArticleForm/index.js
  components/common/DateTimePicker.js
  components/common/Editor/index.js
  components/common/Renderer/index.js
  components/common/Select.js
  constants/api.js
  package-lock.json
  package.json
  redux/ducks/articles.js
  utils/customPropTypes.js
  utils/getters.js
  utils/validators.js
Labels: feature
