Repository babajka/babajka-frontend, pull requests merged in 2018-03, with the labels that each got.

#13 Making Frontend index page match new API
  constants/server.js
  pages/index.js
Labels: fix, not ready yet

#16 Authors fix: optional + localization
  components/articles/ArticlePreview.js
  redux/ducks/articles.js
Labels: fix

#18 Add basic select / dropdown component
  components/common/CoreLayout.js
  components/common/Icon.js
  components/common/Select.js
  components/common/StoriesDecorator.js
  components/common/common.stories.js
  package-lock.json
  package.json
Labels: feature
