Repository babajka/babajka-frontend, pull requests merged in 2019-07, with the labels that each got.

#61 Button group
  .commitlintrc.js
  components/common/Button.js
  components/common/ButtonGroup.js
  components/common/ui/button-group.scss
  components/social/ShareButtons.js
  components/social/social-buttons.scss
  pages/tag.js
Labels: styles

#62 Tag Page Levels Layout
  components/articles/cards/ArticleCard.js
  constants/misc.js
  package-lock.json
  pages/tag.js
  redux/ducks/tags.js
  styles/pages/tag.scss
  utils/getters.js
Labels: fix

#60 Tag Page
  .commitlintrc.js
  components/articles/cards/ArticleCard.js
  components/common/Button.js
  components/common/ButtonGroup.js
  components/common/ui/button-group.scss
  components/social/ShareButtons.js
  components/social/social-buttons.scss
  constants/api.js
  constants/misc.js
  package-lock.json
  pages/tag.js
  redux/ducks/index.js
  redux/ducks/tags.js
  styles/pages/tag.scss
  utils/getters.js
  utils/tags.js
Labels: feature, styles
